// Basic test to confirm that the module auto-generated by `ehters` ABI generator for the
// CIDsOwners contract can be used.
#[test]
fn test_use_cids_owners() {
    use ipfs_cids_owners_contracts::cids_owners;
    let _ = cids_owners::CIDSOWNERS_ABI;
}
